version: '3.9'
services:
    postgres:
        image: postgres:15
        container_name: productcatalog-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: yourpassword
            POSTGRES_DB: ProductCatalogDb
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    pgdata: